### ISSUE TITLE
R9 Fury results

### ISSUE THREAD

**Issue by asmasca** [sebbbi/perftest#10]
R9 Fury Nitro - 56 CU (3584 sp) @1050 MHz 

Adapters found:
0: AMD Radeon (TM) R9 Fury Series
1: Microsoft Basic Render Driver
Using adapter 0

Running 30 warm-up frames and 30 benchmark frames:
.............................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Performance compared to Buffer<RGBA8>.Load random

Buffer<R8>.Load uniform: 8.963ms 3.911x
Buffer<R8>.Load linear: 8.917ms 3.931x
Buffer<R8>.Load random: 35.058ms 1.000x
Buffer<RG8>.Load uniform: 39.416ms 0.889x
Buffer<RG8>.Load linear: 39.447ms 0.889x
Buffer<RG8>.Load random: 39.413ms 0.889x
Buffer<RGBA8>.Load uniform: 35.051ms 1.000x
Buffer<RGBA8>.Load linear: 35.048ms 1.000x
Buffer<RGBA8>.Load random: 35.051ms 1.000x
Buffer<R16f>.Load uniform: 8.898ms 3.939x
Buffer<R16f>.Load linear: 8.909ms 3.934x
Buffer<R16f>.Load random: 35.050ms 1.000x
Buffer<RG16f>.Load uniform: 39.405ms 0.890x
Buffer<RG16f>.Load linear: 39.435ms 0.889x
Buffer<RG16f>.Load random: 39.407ms 0.889x
Buffer<RGBA16f>.Load uniform: 35.041ms 1.000x
Buffer<RGBA16f>.Load linear: 35.043ms 1.000x
Buffer<RGBA16f>.Load random: 35.046ms 1.000x
Buffer<R32f>.Load uniform: 8.897ms 3.940x
Buffer<R32f>.Load linear: 8.910ms 3.934x
Buffer<R32f>.Load random: 35.048ms 1.000x
Buffer<RG32f>.Load uniform: 39.407ms 0.889x
Buffer<RG32f>.Load linear: 39.433ms 0.889x
Buffer<RG32f>.Load random: 39.406ms 0.889x
Buffer<RGBA32f>.Load uniform: 35.043ms 1.000x
Buffer<RGBA32f>.Load linear: 35.045ms 1.000x
Buffer<RGBA32f>.Load random: 39.405ms 0.890x
ByteAddressBuffer.Load uniform: 10.956ms 3.199x
ByteAddressBuffer.Load linear: 9.100ms 3.852x
ByteAddressBuffer.Load random: 35.038ms 1.000x
ByteAddressBuffer.Load2 uniform: 11.070ms 3.166x
ByteAddressBuffer.Load2 linear: 39.413ms 0.889x
ByteAddressBuffer.Load2 random: 39.411ms 0.889x
ByteAddressBuffer.Load3 uniform: 13.534ms 2.590x
ByteAddressBuffer.Load3 linear: 35.047ms 1.000x
ByteAddressBuffer.Load3 random: 70.033ms 0.500x
ByteAddressBuffer.Load4 uniform: 17.944ms 1.953x
ByteAddressBuffer.Load4 linear: 35.072ms 0.999x
ByteAddressBuffer.Load4 random: 39.149ms 0.895x
ByteAddressBuffer.Load2 unaligned uniform: 11.209ms 3.127x
ByteAddressBuffer.Load2 unaligned linear: 39.408ms 0.889x
ByteAddressBuffer.Load2 unaligned random: 39.406ms 0.890x
ByteAddressBuffer.Load4 unaligned uniform: 17.933ms 1.955x
ByteAddressBuffer.Load4 unaligned linear: 35.066ms 1.000x
ByteAddressBuffer.Load4 unaligned random: 43.241ms 0.811x
StructuredBuffer<float>.Load uniform: 12.653ms 2.770x
StructuredBuffer<float>.Load linear: 8.913ms 3.932x
StructuredBuffer<float>.Load random: 35.059ms 1.000x
StructuredBuffer<float2>.Load uniform: 12.799ms 2.739x
StructuredBuffer<float2>.Load linear: 39.445ms 0.889x
StructuredBuffer<float2>.Load random: 39.413ms 0.889x
StructuredBuffer<float4>.Load uniform: 12.834ms 2.731x
StructuredBuffer<float4>.Load linear: 35.049ms 1.000x
StructuredBuffer<float4>.Load random: 39.411ms 0.889x
cbuffer{float4} load uniform: 14.861ms 2.359x
cbuffer{float4} load linear: 35.534ms 0.986x
cbuffer{float4} load random: 39.412ms 0.889x
Texture2D<R8>.Load uniform: 35.063ms 1.000x
Texture2D<R8>.Load linear: 35.038ms 1.000x
Texture2D<R8>.Load random: 35.040ms 1.000x
Texture2D<RG8>.Load uniform: 39.430ms 0.889x
Texture2D<RG8>.Load linear: 39.436ms 0.889x
Texture2D<RG8>.Load random: 39.436ms 0.889x
Texture2D<RGBA8>.Load uniform: 35.059ms 1.000x
Texture2D<RGBA8>.Load linear: 35.061ms 1.000x
Texture2D<RGBA8>.Load random: 35.055ms 1.000x
Texture2D<R16F>.Load uniform: 35.056ms 1.000x
Texture2D<R16F>.Load linear: 35.038ms 1.000x
Texture2D<R16F>.Load random: 35.040ms 1.000x
Texture2D<RG16F>.Load uniform: 39.431ms 0.889x
Texture2D<RG16F>.Load linear: 39.440ms 0.889x
Texture2D<RG16F>.Load random: 39.436ms 0.889x
Texture2D<RGBA16F>.Load uniform: 35.054ms 1.000x
Texture2D<RGBA16F>.Load linear: 35.061ms 1.000x
Texture2D<RGBA16F>.Load random: 70.037ms 0.500x
Texture2D<R32F>.Load uniform: 35.055ms 1.000x
Texture2D<R32F>.Load linear: 35.041ms 1.000x
Texture2D<R32F>.Load random: 35.041ms 1.000x
Texture2D<RG32F>.Load uniform: 39.433ms 0.889x
Texture2D<RG32F>.Load linear: 39.439ms 0.889x
Texture2D<RG32F>.Load random: 70.039ms 0.500x
Texture2D<RGBA32F>.Load uniform: 35.054ms 1.000x
Texture2D<RGBA32F>.Load linear: 52.549ms 0.667x
Texture2D<RGBA32F>.Load random: 70.037ms 0.500x

**Comment by sebbbi** [comment]
Thank you! Added results!
