### ISSUE TITLE
GTX 1070 Ti Results

### ISSUE THREAD

**Issue by SRombauts** [sebbbi/perftest#11]
PerfTest
To select adapter, use: PerfTest.exe [ADAPTER_INDEX]

Adapters found:
0: NVIDIA GeForce GTX 1070 Ti
1: Microsoft Basic Render Driver
Using adapter 0

Running 30 warm-up frames and 30 benchmark frames:
.............................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Performance compared to Buffer<RGBA8>.Load random

Buffer<R8>.Load uniform: 0.845ms 36.835x
Buffer<R8>.Load linear: 29.335ms 1.061x
Buffer<R8>.Load random: 28.981ms 1.074x
Buffer<RG8>.Load uniform: 1.151ms 27.036x
Buffer<RG8>.Load linear: 30.267ms 1.028x
Buffer<RG8>.Load random: 29.359ms 1.060x
Buffer<RGBA8>.Load uniform: 1.534ms 20.286x
Buffer<RGBA8>.Load linear: 31.214ms 0.997x
Buffer<RGBA8>.Load random: 31.118ms 1.000x
Buffer<R16f>.Load uniform: 0.808ms 38.516x
Buffer<R16f>.Load linear: 28.943ms 1.075x
Buffer<R16f>.Load random: 29.870ms 1.042x
Buffer<RG16f>.Load uniform: 1.119ms 27.803x
Buffer<RG16f>.Load linear: 29.458ms 1.056x
Buffer<RG16f>.Load random: 29.904ms 1.041x
Buffer<RGBA16f>.Load uniform: 1.467ms 21.207x
Buffer<RGBA16f>.Load linear: 31.222ms 0.997x
Buffer<RGBA16f>.Load random: 30.223ms 1.030x
Buffer<R32f>.Load uniform: 0.847ms 36.746x
Buffer<R32f>.Load linear: 30.240ms 1.029x
Buffer<R32f>.Load random: 28.963ms 1.074x
Buffer<RG32f>.Load uniform: 1.087ms 28.615x
Buffer<RG32f>.Load linear: 30.391ms 1.024x
Buffer<RG32f>.Load random: 29.475ms 1.056x
Buffer<RGBA32f>.Load uniform: 1.434ms 21.706x
Buffer<RGBA32f>.Load linear: 59.394ms 0.524x
Buffer<RGBA32f>.Load random: 57.593ms 0.540x
ByteAddressBuffer.Load uniform: 18.151ms 1.714x
ByteAddressBuffer.Load linear: 18.451ms 1.686x
ByteAddressBuffer.Load random: 21.305ms 1.461x
ByteAddressBuffer.Load2 uniform: 41.123ms 0.757x
ByteAddressBuffer.Load2 linear: 40.461ms 0.769x
ByteAddressBuffer.Load2 random: 49.244ms 0.632x
ByteAddressBuffer.Load3 uniform: 44.836ms 0.694x
ByteAddressBuffer.Load3 linear: 65.966ms 0.472x
ByteAddressBuffer.Load3 random: 77.712ms 0.400x
ByteAddressBuffer.Load4 uniform: 58.439ms 0.532x
ByteAddressBuffer.Load4 linear: 97.260ms 0.320x
ByteAddressBuffer.Load4 random: 174.779ms 0.178x
ByteAddressBuffer.Load2 unaligned uniform: 41.147ms 0.756x
ByteAddressBuffer.Load2 unaligned linear: 40.483ms 0.769x
ByteAddressBuffer.Load2 unaligned random: 55.911ms 0.557x
ByteAddressBuffer.Load4 unaligned uniform: 58.126ms 0.535x
ByteAddressBuffer.Load4 unaligned linear: 99.081ms 0.314x
ByteAddressBuffer.Load4 unaligned random: 179.514ms 0.173x
StructuredBuffer<float>.Load uniform: 0.887ms 35.091x
StructuredBuffer<float>.Load linear: 29.878ms 1.042x
StructuredBuffer<float>.Load random: 29.408ms 1.058x
StructuredBuffer<float2>.Load uniform: 1.141ms 27.279x
StructuredBuffer<float2>.Load linear: 30.575ms 1.018x
StructuredBuffer<float2>.Load random: 28.985ms 1.074x
StructuredBuffer<float4>.Load uniform: 1.523ms 20.436x
StructuredBuffer<float4>.Load linear: 58.493ms 0.532x
StructuredBuffer<float4>.Load random: 58.546ms 0.532x
cbuffer{float4} load uniform: 1.390ms 22.394x
cbuffer{float4} load linear: 684.120ms 0.045x
cbuffer{float4} load random: 273.085ms 0.114x
Texture2D<R8>.Load uniform: 1.627ms 19.125x
Texture2D<R8>.Load linear: 28.924ms 1.076x
Texture2D<R8>.Load random: 28.923ms 1.076x
Texture2D<RG8>.Load uniform: 1.378ms 22.577x
Texture2D<RG8>.Load linear: 29.041ms 1.072x
Texture2D<RG8>.Load random: 28.938ms 1.075x
Texture2D<RGBA8>.Load uniform: 1.563ms 19.914x
Texture2D<RGBA8>.Load linear: 30.666ms 1.015x
Texture2D<RGBA8>.Load random: 30.334ms 1.026x
Texture2D<R16F>.Load uniform: 1.313ms 23.704x
Texture2D<R16F>.Load linear: 28.961ms 1.074x
Texture2D<R16F>.Load random: 28.968ms 1.074x
Texture2D<RG16F>.Load uniform: 1.360ms 22.883x
Texture2D<RG16F>.Load linear: 29.048ms 1.071x
Texture2D<RG16F>.Load random: 28.926ms 1.076x
Texture2D<RGBA16F>.Load uniform: 1.501ms 20.729x
Texture2D<RGBA16F>.Load linear: 30.649ms 1.015x
Texture2D<RGBA16F>.Load random: 57.629ms 0.540x
Texture2D<R32F>.Load uniform: 1.384ms 22.477x
Texture2D<R32F>.Load linear: 28.955ms 1.075x
Texture2D<R32F>.Load random: 28.968ms 1.074x
Texture2D<RG32F>.Load uniform: 1.408ms 22.101x
Texture2D<RG32F>.Load linear: 29.056ms 1.071x
Texture2D<RG32F>.Load random: 57.672ms 0.540x
Texture2D<RGBA32F>.Load uniform: 1.538ms 20.232x
Texture2D<RGBA32F>.Load linear: 57.653ms 0.540x
Texture2D<RGBA32F>.Load random: 57.557ms 0.541x

**Comment by sebbbi** [comment]
Thank you! Added results!
