### ISSUE TITLE
Could you clarify that the bandwidth used?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [sebbbi/perftest#18]
Right now I see the timings, but the problem is that a RG8 load is 8x less memory being fetched than a RGBA32F

So its really hard to translate this to a meaningful and useful number if you're trying to decide on the format to store armature bone matrices for vertex skinning.

**Comment by sebbbi** [comment]
This benchmark is measuring peak load/store rate from L1$. It's useful when you have highly coherent data that fits to the GPU caches. 

This benchmark is NOT useful for measuring memory bandwidth bound cases. In those cases you should simply try to reduce the data size and look at the memory bandwidth numbers given by your GPU vendor. Those are pretty accurate.
