### ISSUE TITLE
Application crashes when run from command line

### ISSUE THREAD

**Issue by boxerab** [sebbbi/perftest#2]
Assertion failed: f, file file.cpp, line 19

Running from Visual Studio works just fine.

**Comment by sebbbi** [comment]
the executable output folder is not in the default working directory. It doesn't find the shaders. If you want to package a build, copy the exe to the root and the shaders directory in the same folder.

**Comment by sebbbi** [comment]
I will add a .bat file to package exe and shaders together (create build folder).

**Comment by boxerab** [comment]
Thanks, that makes sense.

**Comment by sebbbi** [comment]
Added a bat file.
