### ISSUE TITLE
RTX 2080 results

### ISSUE THREAD

**Issue by cdyk** [sebbbi/perftest#7]
C:\Code\perftest\perftest> ..\x64\Release\perftest.exe
PerfTest
To select adapter, use: PerfTest.exe [ADAPTER_INDEX]

Adapters found:
0: NVIDIA GeForce RTX 2080
1: Microsoft Basic Render Driver
Using adapter 0

Running 30 warm-up frames and 30 benchmark frames:
.............................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Performance compared to Buffer<RGBA8>.Load random

Buffer<R8>.Load uniform: 0.584ms 40.050x
Buffer<R8>.Load linear: 22.632ms 1.033x
Buffer<R8>.Load random: 22.652ms 1.032x
Buffer<RG8>.Load uniform: 0.702ms 33.313x
Buffer<RG8>.Load linear: 22.656ms 1.032x
Buffer<RG8>.Load random: 24.384ms 0.959x
Buffer<RGBA8>.Load uniform: 1.021ms 22.896x
Buffer<RGBA8>.Load linear: 23.277ms 1.004x
Buffer<RGBA8>.Load random: 23.380ms 1.000x
Buffer<R16f>.Load uniform: 0.575ms 40.642x
Buffer<R16f>.Load linear: 23.506ms 0.995x
Buffer<R16f>.Load random: 23.431ms 0.998x
Buffer<RG16f>.Load uniform: 0.701ms 33.344x
Buffer<RG16f>.Load linear: 23.438ms 0.998x
Buffer<RG16f>.Load random: 24.307ms 0.962x
Buffer<RGBA16f>.Load uniform: 0.998ms 23.432x
Buffer<RGBA16f>.Load linear: 24.054ms 0.972x
Buffer<RGBA16f>.Load random: 24.884ms 0.940x
Buffer<R32f>.Load uniform: 0.575ms 40.681x
Buffer<R32f>.Load linear: 22.650ms 1.032x
Buffer<R32f>.Load random: 26.428ms 0.885x
Buffer<RG32f>.Load uniform: 0.712ms 32.833x
Buffer<RG32f>.Load linear: 22.647ms 1.032x
Buffer<RG32f>.Load random: 24.314ms 0.962x
Buffer<RGBA32f>.Load uniform: 1.004ms 23.282x
Buffer<RGBA32f>.Load linear: 48.893ms 0.478x
Buffer<RGBA32f>.Load random: 45.172ms 0.518x
ByteAddressBuffer.Load uniform: 10.761ms 2.173x
ByteAddressBuffer.Load linear: 10.822ms 2.160x
ByteAddressBuffer.Load random: 10.418ms 2.244x
ByteAddressBuffer.Load2 uniform: 13.868ms 1.686x
ByteAddressBuffer.Load2 linear: 25.584ms 0.914x
ByteAddressBuffer.Load2 random: 14.147ms 1.653x
ByteAddressBuffer.Load3 uniform: 20.011ms 1.168x
ByteAddressBuffer.Load3 linear: 26.011ms 0.899x
ByteAddressBuffer.Load3 random: 21.576ms 1.084x
ByteAddressBuffer.Load4 uniform: 27.127ms 0.862x
ByteAddressBuffer.Load4 linear: 64.374ms 0.363x
ByteAddressBuffer.Load4 random: 54.111ms 0.432x
ByteAddressBuffer.Load2 unaligned uniform: 20.559ms 1.137x
ByteAddressBuffer.Load2 unaligned linear: 32.326ms 0.723x
ByteAddressBuffer.Load2 unaligned random: 14.630ms 1.598x
ByteAddressBuffer.Load4 unaligned uniform: 30.289ms 0.772x
ByteAddressBuffer.Load4 unaligned linear: 61.641ms 0.379x
ByteAddressBuffer.Load4 unaligned random: 53.058ms 0.441x
StructuredBuffer<float>.Load uniform: 13.206ms 1.770x
StructuredBuffer<float>.Load linear: 12.844ms 1.820x
StructuredBuffer<float>.Load random: 10.077ms 2.320x
StructuredBuffer<float2>.Load uniform: 11.750ms 1.990x
StructuredBuffer<float2>.Load linear: 24.699ms 0.947x
StructuredBuffer<float2>.Load random: 15.797ms 1.480x
StructuredBuffer<float4>.Load uniform: 23.440ms 0.997x
StructuredBuffer<float4>.Load linear: 36.338ms 0.643x
StructuredBuffer<float4>.Load random: 35.524ms 0.658x
cbuffer{float4} load uniform: 0.906ms 25.802x
cbuffer{float4} load linear: 541.480ms 0.043x
cbuffer{float4} load random: 195.860ms 0.119x
Texture2D<R8>.Load uniform: 0.670ms 34.905x
Texture2D<R8>.Load linear: 23.513ms 0.994x
Texture2D<R8>.Load random: 23.501ms 0.995x
Texture2D<RG8>.Load uniform: 0.831ms 28.125x
Texture2D<RG8>.Load linear: 22.675ms 1.031x
Texture2D<RG8>.Load random: 24.535ms 0.953x
Texture2D<RGBA8>.Load uniform: 1.374ms 17.016x
Texture2D<RGBA8>.Load linear: 23.982ms 0.975x
Texture2D<RGBA8>.Load random: 24.520ms 0.953x
Texture2D<R16F>.Load uniform: 0.632ms 36.995x
Texture2D<R16F>.Load linear: 22.657ms 1.032x
Texture2D<R16F>.Load random: 24.281ms 0.963x
Texture2D<RG16F>.Load uniform: 0.822ms 28.430x
Texture2D<RG16F>.Load linear: 23.423ms 0.998x
Texture2D<RG16F>.Load random: 22.666ms 1.032x
Texture2D<RGBA16F>.Load uniform: 1.363ms 17.155x
Texture2D<RGBA16F>.Load linear: 23.045ms 1.015x
Texture2D<RGBA16F>.Load random: 46.803ms 0.500x
Texture2D<R32F>.Load uniform: 4.187ms 5.583x
Texture2D<R32F>.Load linear: 27.111ms 0.862x
Texture2D<R32F>.Load random: 23.073ms 1.013x
Texture2D<RG32F>.Load uniform: 1.543ms 15.151x
Texture2D<RG32F>.Load linear: 25.248ms 0.926x
Texture2D<RG32F>.Load random: 45.187ms 0.517x
Texture2D<RGBA32F>.Load uniform: 1.376ms 16.986x
Texture2D<RGBA32F>.Load linear: 46.115ms 0.507x
Texture2D<RGBA32F>.Load random: 45.166ms 0.518x
PS C:\Code\perftest\perftest>

**Comment by sebbbi** [comment]
Thank you! Added results!
