### ISSUE TITLE
New Titan V Results

### ISSUE THREAD

**Issue by ajmiles** [sebbbi/perftest#8]
PerfTest
To select adapter, use: PerfTest.exe [ADAPTER_INDEX]

Adapters found:
0: NVIDIA TITAN V
1: Intel(R) HD Graphics 530
2: Microsoft Basic Render Driver
Using adapter 0

Running 30 warm-up frames and 30 benchmark frames:
.............................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Performance compared to Buffer[RGBA8].Load random

Buffer[R8].Load uniform: 2.241ms 8.139x
Buffer[R8].Load linear: 14.806ms 1.232x
Buffer[R8].Load random: 16.514ms 1.104x
Buffer[RG8].Load uniform: 4.576ms 3.985x
Buffer[RG8].Load linear: 16.397ms 1.112x
Buffer[RG8].Load random: 16.707ms 1.092x
Buffer[RGBA8].Load uniform: 5.155ms 3.538x
Buffer[RGBA8].Load linear: 16.726ms 1.090x
Buffer[RGBA8].Load random: 18.236ms 1.000x
Buffer[R16f].Load uniform: 2.807ms 6.497x
Buffer[R16f].Load linear: 14.771ms 1.235x
Buffer[R16f].Load random: 16.857ms 1.082x
Buffer[RG16f].Load uniform: 4.128ms 4.418x
Buffer[RG16f].Load linear: 16.155ms 1.129x
Buffer[RG16f].Load random: 15.140ms 1.205x
Buffer[RGBA16f].Load uniform: 4.747ms 3.841x
Buffer[RGBA16f].Load linear: 17.517ms 1.041x
Buffer[RGBA16f].Load random: 17.727ms 1.029x
Buffer[R32f].Load uniform: 2.630ms 6.935x
Buffer[R32f].Load linear: 17.341ms 1.052x
Buffer[R32f].Load random: 15.922ms 1.145x
Buffer[RG32f].Load uniform: 4.769ms 3.824x
Buffer[RG32f].Load linear: 15.745ms 1.158x
Buffer[RG32f].Load random: 15.801ms 1.154x
Buffer[RGBA32f].Load uniform: 4.772ms 3.822x
Buffer[RGBA32f].Load linear: 29.343ms 0.621x
Buffer[RGBA32f].Load random: 29.427ms 0.620x
ByteAddressBuffer.Load uniform: 8.948ms 2.038x
ByteAddressBuffer.Load linear: 8.722ms 2.091x
ByteAddressBuffer.Load random: 10.403ms 1.753x
ByteAddressBuffer.Load2 uniform: 10.132ms 1.800x
ByteAddressBuffer.Load2 linear: 11.406ms 1.599x
ByteAddressBuffer.Load2 random: 10.999ms 1.658x
ByteAddressBuffer.Load3 uniform: 12.638ms 1.443x
ByteAddressBuffer.Load3 linear: 13.708ms 1.330x
ByteAddressBuffer.Load3 random: 14.081ms 1.295x
ByteAddressBuffer.Load4 uniform: 15.421ms 1.183x
ByteAddressBuffer.Load4 linear: 26.412ms 0.690x
ByteAddressBuffer.Load4 random: 18.078ms 1.009x
ByteAddressBuffer.Load2 unaligned uniform: 11.076ms 1.647x
ByteAddressBuffer.Load2 unaligned linear: 11.474ms 1.589x
ByteAddressBuffer.Load2 unaligned random: 12.227ms 1.492x
ByteAddressBuffer.Load4 unaligned uniform: 15.817ms 1.153x
ByteAddressBuffer.Load4 unaligned linear: 25.894ms 0.704x
ByteAddressBuffer.Load4 unaligned random: 18.138ms 1.005x
StructuredBuffer[float].Load uniform: 6.606ms 2.761x
StructuredBuffer[float].Load linear: 6.555ms 2.782x
StructuredBuffer[float].Load random: 9.063ms 2.012x
StructuredBuffer[float2].Load uniform: 8.332ms 2.189x
StructuredBuffer[float2].Load linear: 8.545ms 2.134x
StructuredBuffer[float2].Load random: 7.271ms 2.508x
StructuredBuffer[float4].Load uniform: 8.890ms 2.051x
StructuredBuffer[float4].Load linear: 9.650ms 1.890x
StructuredBuffer[float4].Load random: 9.677ms 1.885x
cbuffer{float4} load uniform: 1.381ms 13.202x
cbuffer{float4} load linear: 320.961ms 0.057x
cbuffer{float4} load random: 150.072ms 0.122x
Texture2D[R8].Load uniform: 4.481ms 4.070x
Texture2D[R8].Load linear: 15.953ms 1.143x
Texture2D[R8].Load random: 15.058ms 1.211x
Texture2D[RG8].Load uniform: 4.594ms 3.970x
Texture2D[RG8].Load linear: 14.838ms 1.229x
Texture2D[RG8].Load random: 14.938ms 1.221x
Texture2D[RGBA8].Load uniform: 5.140ms 3.548x
Texture2D[RGBA8].Load linear: 14.915ms 1.223x
Texture2D[RGBA8].Load random: 15.031ms 1.213x
Texture2D[R16F].Load uniform: 5.748ms 3.173x
Texture2D[R16F].Load linear: 15.321ms 1.190x
Texture2D[R16F].Load random: 15.044ms 1.212x
Texture2D[RG16F].Load uniform: 4.609ms 3.957x
Texture2D[RG16F].Load linear: 14.918ms 1.222x
Texture2D[RG16F].Load random: 14.851ms 1.228x
Texture2D[RGBA16F].Load uniform: 5.182ms 3.519x
Texture2D[RGBA16F].Load linear: 14.915ms 1.223x
Texture2D[RGBA16F].Load random: 29.841ms 0.611x
Texture2D[R32F].Load uniform: 4.462ms 4.087x
Texture2D[R32F].Load linear: 15.615ms 1.168x
Texture2D[R32F].Load random: 15.519ms 1.175x
Texture2D[RG32F].Load uniform: 4.585ms 3.977x
Texture2D[RG32F].Load linear: 16.651ms 1.095x
Texture2D[RG32F].Load random: 29.710ms 0.614x
Texture2D[RGBA32F].Load uniform: 5.163ms 3.532x
Texture2D[RGBA32F].Load linear: 29.970ms 0.608x
Texture2D[RGBA32F].Load random: 29.358ms 0.621x

**Comment by sebbbi** [comment]
Thank you! Added results!
