### ISSUE TITLE
GTX 980 Ti Results

### ISSUE THREAD

**Issue by SRombauts** [sebbbi/perftest#9]
PerfTest
To select adapter, use: PerfTest.exe [ADAPTER_INDEX]

Adapters found:
0: NVIDIA GeForce GTX 980 Ti
1: Microsoft Basic Render Driver
Using adapter 0

Running 30 warm-up frames and 30 benchmark frames:
.............................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Performance compared to Buffer<RGBA8>.Load random

Buffer<R8>.Load uniform: 1.249ms 28.812x
Buffer<R8>.Load linear: 34.105ms 1.055x
Buffer<R8>.Load random: 34.187ms 1.053x
Buffer<RG8>.Load uniform: 1.847ms 19.485x
Buffer<RG8>.Load linear: 34.106ms 1.055x
Buffer<RG8>.Load random: 34.477ms 1.044x
Buffer<RGBA8>.Load uniform: 2.452ms 14.680x
Buffer<RGBA8>.Load linear: 35.773ms 1.006x
Buffer<RGBA8>.Load random: 35.996ms 1.000x
Buffer<R16f>.Load uniform: 1.491ms 24.148x
Buffer<R16f>.Load linear: 34.077ms 1.056x
Buffer<R16f>.Load random: 34.463ms 1.044x
Buffer<RG16f>.Load uniform: 1.916ms 18.785x
Buffer<RG16f>.Load linear: 34.229ms 1.052x
Buffer<RG16f>.Load random: 34.597ms 1.040x
Buffer<RGBA16f>.Load uniform: 2.519ms 14.291x
Buffer<RGBA16f>.Load linear: 35.787ms 1.006x
Buffer<RGBA16f>.Load random: 35.996ms 1.000x
Buffer<R32f>.Load uniform: 1.478ms 24.350x
Buffer<R32f>.Load linear: 34.098ms 1.056x
Buffer<R32f>.Load random: 34.353ms 1.048x
Buffer<RG32f>.Load uniform: 1.845ms 19.514x
Buffer<RG32f>.Load linear: 34.138ms 1.054x
Buffer<RG32f>.Load random: 34.495ms 1.044x
Buffer<RGBA32f>.Load uniform: 2.374ms 15.163x
Buffer<RGBA32f>.Load linear: 67.973ms 0.530x
Buffer<RGBA32f>.Load random: 68.054ms 0.529x
ByteAddressBuffer.Load uniform: 21.403ms 1.682x
ByteAddressBuffer.Load linear: 21.906ms 1.643x
ByteAddressBuffer.Load random: 24.336ms 1.479x
ByteAddressBuffer.Load2 uniform: 45.620ms 0.789x
ByteAddressBuffer.Load2 linear: 55.815ms 0.645x
ByteAddressBuffer.Load2 random: 48.744ms 0.738x
ByteAddressBuffer.Load3 uniform: 52.929ms 0.680x
ByteAddressBuffer.Load3 linear: 79.057ms 0.455x
ByteAddressBuffer.Load3 random: 93.636ms 0.384x
ByteAddressBuffer.Load4 uniform: 68.510ms 0.525x
ByteAddressBuffer.Load4 linear: 114.561ms 0.314x
ByteAddressBuffer.Load4 random: 209.280ms 0.172x
ByteAddressBuffer.Load2 unaligned uniform: 45.640ms 0.789x
ByteAddressBuffer.Load2 unaligned linear: 55.802ms 0.645x
ByteAddressBuffer.Load2 unaligned random: 48.717ms 0.739x
ByteAddressBuffer.Load4 unaligned uniform: 68.685ms 0.524x
ByteAddressBuffer.Load4 unaligned linear: 115.244ms 0.312x
ByteAddressBuffer.Load4 unaligned random: 210.358ms 0.171x
StructuredBuffer<float>.Load uniform: 1.116ms 32.267x
StructuredBuffer<float>.Load linear: 34.094ms 1.056x
StructuredBuffer<float>.Load random: 34.092ms 1.056x
StructuredBuffer<float2>.Load uniform: 1.569ms 22.942x
StructuredBuffer<float2>.Load linear: 34.143ms 1.054x
StructuredBuffer<float2>.Load random: 34.125ms 1.055x
StructuredBuffer<float4>.Load uniform: 2.087ms 17.245x
StructuredBuffer<float4>.Load linear: 67.959ms 0.530x
StructuredBuffer<float4>.Load random: 67.950ms 0.530x
cbuffer{float4} load uniform: 1.298ms 27.733x
cbuffer{float4} load linear: 798.703ms 0.045x
cbuffer{float4} load random: 324.356ms 0.111x
Texture2D<R8>.Load uniform: 1.962ms 18.351x
Texture2D<R8>.Load linear: 34.027ms 1.058x
Texture2D<R8>.Load random: 34.029ms 1.058x
Texture2D<RG8>.Load uniform: 1.994ms 18.054x
Texture2D<RG8>.Load linear: 34.334ms 1.048x
Texture2D<RG8>.Load random: 34.102ms 1.056x
Texture2D<RGBA8>.Load uniform: 2.247ms 16.018x
Texture2D<RGBA8>.Load linear: 36.077ms 0.998x
Texture2D<RGBA8>.Load random: 35.930ms 1.002x
Texture2D<R16F>.Load uniform: 2.021ms 17.814x
Texture2D<R16F>.Load linear: 34.040ms 1.057x
Texture2D<R16F>.Load random: 34.021ms 1.058x
Texture2D<RG16F>.Load uniform: 2.020ms 17.822x
Texture2D<RG16F>.Load linear: 34.308ms 1.049x
Texture2D<RG16F>.Load random: 34.095ms 1.056x
Texture2D<RGBA16F>.Load uniform: 2.199ms 16.372x
Texture2D<RGBA16F>.Load linear: 36.074ms 0.998x
Texture2D<RGBA16F>.Load random: 68.064ms 0.529x
Texture2D<R32F>.Load uniform: 2.014ms 17.869x
Texture2D<R32F>.Load linear: 34.042ms 1.057x
Texture2D<R32F>.Load random: 34.028ms 1.058x
Texture2D<RG32F>.Load uniform: 1.981ms 18.166x
Texture2D<RG32F>.Load linear: 34.320ms 1.049x
Texture2D<RG32F>.Load random: 67.948ms 0.530x
Texture2D<RGBA32F>.Load uniform: 2.064ms 17.440x
Texture2D<RGBA32F>.Load linear: 67.974ms 0.530x
Texture2D<RGBA32F>.Load random: 68.049ms 0.529x

**Comment by sebbbi** [comment]
Thank you! Added results!
